### ISSUE TITLE
Crash when doing a text copy in Yam

### ISSUE THREAD

**Issue by pferrucci** [amiga-mui/texteditor#18]
mcc version: 15.47
100 % reproducible

When I select text in Yam, it always crashes with:
Stack trace:
    LIBS:mui/TextEditor.mcc:SetDefaultColor()+0x8 (section 1 @ 0x49E4)
    LIBS:mui/TextEditor.mcc:ClipboardServer()+0x248 (section 1 @ 0x2D40)
    native kernel module kernel.debug+0x00067db0
    native kernel module kernel.debug+0x00067df8

PPC disassembly:
 7f5ed9e0: 2c030000   cmpwi             r3,0
 7f5ed9e4: 41820010   beq-              0x7F5ED9F4
*7f5ed9e8: a923043c   lha               r9,1084(r3)
 7f5ed9ec: 2f890001   cmpwi             cr7,r9,1
 7f5ed9f0: 419e0018   beq-              cr7,0x7F5EDA08

Full log attached.
[Crashlog_TextEditor.mcc clipboard server_2016-11-12_18-55-08.txt](https://github.com/amiga-mui/texteditor/files/587369/Crashlog_TextEditor.mcc.clipboard.server_2016-11-12_18-55-08.txt)

**Comment by tboeckel** [comment]
You are repeating yourself. You opened #5 already about exactly the same issue. Fixed binaries can be found in #4. Version 15.48 will still take a while until it will be released.
