### ISSUE TITLE
Implement horizontal scrolling

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#2]
When setting MUIA_TextEditor_WrapMode to MUIV_TextEditor_WrapMode_NoWrap there is no horizontal scrolling. Instead, characters are added to the beginning of the same line which looks ugly and makes this attribute rather useless. There should be a possibility to have horizontal scrolling with TextEditor.mcc as well. This is a fundamental feature which every TextEditor class needs IMHO. It's about time that TextEditor.mcc supports this as well :)

**Comment by alpyre** [comment]
I was in the middle of a MUI project, which I started with the assumption that TextEditor.mcc supports this by reading a NoWrap mode is available in the autodoc, found out that it doesn't, came here to submit an issue, but saw that "softwarefailure" already did it. :)

**Comment by jens-maus** [comment]
Please note that there have been some progress lately regarding horizontal scrolling. We are currently reviewing a pull request by @alpyre which should implement this functionality. See https://github.com/amiga-mui/texteditor/pull/7

**Comment by jens-maus** [comment]
Horizontal scrolling is now implemented in the very latest sources in our repository thanks to @alpyre

**Comment by afalkenhahn** [comment]
That's great to hear! Can I have some binaries (OS3 and OS4 please) and autodocs to test and implement this in RapaGUI and MUI Royale?

**Comment by afalkenhahn** [comment]
That's great to hear! Can I have some binaries (OS3 and OS4 please) and autodocs to test and implement this in RapaGUI and MUI Royale?

**Comment by alpyre** [comment]
@softwarefailure We are working on some bugs and having functionality discussions. Please wait for the next release (I believe it will be quite soon). Thanks.
