### ISSUE TITLE
Version 15.51 crashes YAM after change of message selection

### ISSUE THREAD

**Issue by Gerbinist** [amiga-mui/texteditor#23]
YAM version used: 2.10-dev [OS3/m68k], 23-02-2019
TextEditor version: 15.51 (issue not present with 15.50)

Steps to reproduce the issue:
1. Open YAM (all still OK, YAM opens in a folder with multiple emails)
2. Select a different message in the folder (with the mouse or arrow down for instance)
3. YAM crashes

Two hits are produced:

> WORD READ from FFFFFF88 (INST)                 PC: FFFFFF88
USP : 785810C4 SR: 0000  (U0)(-)(-)  TCB: 78569E98
Data: 78B90000 00000000 00000230 78580000 78A30000 0000008C 0000000B 00000002
Addr: 78B922A4 78581104 00000230 00000604 00000030 78581240 00000000 7820DFE8
Stck: 7868D2E2 00000017 78A348E4 00000120 00000017 00000000 78730AB0 00000017
Stck: 000000B3 00000030 78581240 78000B4C 000000B3 00000000 78B922A4 78731C7C
Stck: 00000000 78731C7C 00000000 00000000 00000000 00000000 FF0100FF 00000F00
Stck: 0001FFFF 008B0007 EA2A2A2A 2A2A2A2A 00000000 782A7B4A 01000009 00060006
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Stck: 00000000 008A0009 0000FFFA 00890002 00000000 7868DF5C 78730AB0 78A348E4
Stck: 00000017 00000000 80000000 00000001 7858133C 0000001A 00000001 78730001
Stck: 00000000 00000000 78A34884 00000003 786910A4 78A30000 000078A3 48B40000
Stck: 0009B2E6 78580001 786AB4E0 00000000 00000000 00000000 000001D3 00000000
Stck: 78A3491E 78A34972 00000000 00000000 00000000 0000001A 0000004A 78A348B4
Stck: 00017560 78A10000 008A0000 00090000 01200000 00000000 01AA0000 00090000
Stck: 00020000 00000001 0000BDAE 78A3480C 00000001 7858133C 78A1B240 7858129C
Stck: 7868B612 78A1B240 00000000 78A34884 00000003 00000001 78A1B374 7858133C
Stck: 7855A560 78580000 78730000 78B91C00 78A1B656 78A1B240 78A1B1B8 780001F0
Stck: 7868FD00 78A3480C 00000001 00000000 7858133C 78A1B656 78581354 7867FFBC
Stck: 78A1B240 00000001 00000000 00000019 00000000 78A1B240 78A1B240 7858162C
Name: "YAM"

> Exception !!   00000002     TCB: 78569E98     CTX: 78104FC0     SSP: 7820DFE8
USP : 785810C4 SR: 0000  (U0)(-)(-)  TCB: 78569E98
Data: 78B90000 00000000 00000230 78580000 78A30000 0000008C 0000000B 00000002
Addr: 78B922A4 78581104 00000230 00000604 00000030 78581240 00000000 7820DFE8
Stck: 7868D2E2 00000017 78A348E4 00000120 00000017 00000000 78730AB0 00000017
Stck: 000000B3 00000030 78581240 78000B4C 000000B3 00000000 78B922A4 78731C7C
Stck: 00000000 78731C7C 00000000 00000000 00000000 00000000 FF0100FF 00000F00
Stck: 0001FFFF 008B0007 EA2A2A2A 2A2A2A2A 00000000 782A7B4A 01000009 00060006
Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
Stck: 00000000 008A0009 0000FFFA 00890002 00000000 7868DF5C 78730AB0 78A348E4
Stck: 00000017 00000000 80000000 00000001 7858133C 0000001A 00000001 78730001
Stck: 00000000 00000000 78A34884 00000003 786910A4 78A30000 000078A3 48B40000
Stck: 0009B2E6 78580001 786AB4E0 00000000 00000000 00000000 000001D3 00000000
Stck: 78A3491E 78A34972 00000000 00000000 00000000 0000001A 0000004A 78A348B4
Stck: 00017560 78A10000 008A0000 00090000 01200000 00000000 01AA0000 00090000
Stck: 00020000 00000001 0000BDAE 78A3480C 00000001 7858133C 78A1B240 7858129C
Stck: 7868B612 78A1B240 00000000 78A34884 00000003 00000001 78A1B374 7858133C
Stck: 7855A560 78580000 78730000 78B91C00 78A1B656 78A1B240 78A1B1B8 780001F0
Stck: 7868FD00 78A3480C 00000001 00000000 7858133C 78A1B656 78581354 7867FFBC
Stck: 78A1B240 00000001 00000000 00000019 00000000 78A1B240 78A1B240 7858162C
Name: "YAM"

Additional information:

>  - "YAM"  Hunk 0000 Offset 0012CE58
----> 7855A600 - "YAM"  Hunk 0000 Offset 0012CE58
----> 782DB1F0 - "LIBS:muimaster.library"  Hunk 0000 Offset 0000AA70
----> 7868F404 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003EC4
----> 7855A600 - "YAM"  Hunk 0000 Offset 0012CE58
----> 786A1E9C - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001695C
----> 78680000 - "LIBS:mui/NListtree.mcc"  Hunk 0000 Offset 0000C770
----> 7868ED88 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003848
----> 7868F4DA - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003F9A
----> 7855A600 - "YAM"  Hunk 0000 Offset 0012CE58
----> 782B13A0 - "LIBS:muilowlevel.library"  Hunk 0001 Offset 00000000
----> 7868F0CE - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003B8E
----> 782D610C - "LIBS:muimaster.library"  Hunk 0000 Offset 0000598C
----> 784DEC9C - "YAM"  Hunk 0000 Offset 000B14F4
----> 7855ABE2 - "YAM"  Hunk 0000 Offset 0012D43A
----> 7855AB28 - "YAM"  Hunk 0000 Offset 0012D380
----> 784DED8E - "YAM"  Hunk 0000 Offset 000B15E6
----> 782D610C - "LIBS:muimaster.library"  Hunk 0000 Offset 0000598C
----> 7830126E - "LIBS:muilowlevel.library"  Hunk 0000 Offset 00000E2E
----> 78300F6C - "LIBS:muilowlevel.library"  Hunk 0000 Offset 00000B2C
Name: "YAM"

Please let me know if I need to provide additional details.

**Comment by tboeckel** [comment]
I just tried reading mail with YAM my self and for me everything is working absolutely stable. Hence a bit more information about YAM's settings would be fine. Are you using the embedded read pane or a separate window for reading mails? Are using any other special settings (YAM or TE.mcc)?

**Comment by Gerbinist** [comment]
I can also reproduce the issue (without starting YAM) when going to MUI Preferences and selecting the Sample tab at TextEditor. MUI crashes as soon as I click on the Sample tab.

    11.Ram Disk:> version MUI:Libs/muimaster.library full
    muimaster.library 19.35 (12-02-1997)
    ©1992-1997 Stefan Stuntz
    11.Ram Disk:> version MUI:Libs/mui/TextEditor.mcc full
    TextEditor.mcc 15.51 (29-10-2018)
    Copyright (C) 2005-2018 TextEditor.mcc Open Source Team [OS3/m68k]
    11.Ram Disk:> version MUI:Libs/mui/TextEditor.mcp full
    TextEditor.mcp 15.51 (29-10-2018)
    Copyright (C) 2005-2018 TextEditor.mcc Open Source Team [OS3/m68k]

No other special settings worth mentioning (didn't touch default TE settings).

    ----> 7829721A - "FONTS:XHelvetica/11"  Hunk 0000 Offset 0000003A
    ----> 7861E77C - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 000110C4
    ----> 786218C4 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001420C
    ----> 7861BE32 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0000E77A
    ----> 78624014 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001695C
    ----> 78610F3A - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003882
    ----> 78611652 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003F9A
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 78611246 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003B8E
    ----> 782D60EC - "LIBS:muimaster.library"  Hunk 0000 Offset 0000598C
    ----> 782F6BFE - "LIBS:muimaster.library"  Hunk 0000 Offset 0002649E
    ----> 782D83FC - "LIBS:muimaster.library"  Hunk 0000 Offset 00007C9C
    ----> 782D7DE0 - "LIBS:muimaster.library"  Hunk 0000 Offset 00007680
    ----> 782D4850 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
    ----> 782D4894 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004134
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 782D7FC0 - "LIBS:muimaster.library"  Hunk 0000 Offset 00007860
    ----> 782D7DE0 - "LIBS:muimaster.library"  Hunk 0000 Offset 00007680
    ----> 782D7D28 - "LIBS:muimaster.library"  Hunk 0000 Offset 000075C8
    ----> 782D4850 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
    ----> 782D4894 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004134
    ----> 782D4850 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 782D4894 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004134
    ----> 782D4850 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 782D5C60 - "LIBS:muimaster.library"  Hunk 0000 Offset 00005500
    ----> 782B1758 - "LIBS:muilowlevel.library"  Hunk 0001 Offset 00000000
    ----> 7830124E - "LIBS:muilowlevel.library"  Hunk 0000 Offset 00000E2E
    ----> 78300F4C - "LIBS:muilowlevel.library"  Hunk 0000 Offset 00000B2C
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 782D2B4E - "LIBS:muimaster.library"  Hunk 0000 Offset 000023EE
    ----> 782F7280 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
    ----> 782D6DDC - "LIBS:muimaster.library"  Hunk 0000 Offset 0000667C
    ----> 782D698E - "LIBS:muimaster.library"  Hunk 0000 Offset 0000622E
    ----> 782D4850 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
    Name: "MUI"

Produced hits:

    WORD READ from FFFFFF88 (INST)                 PC: FFFFFF88
    USP : 78465250 SR: 0000  (U0)(-)(-)  TCB: 78460AE8
    Data: 78650000 00000000 00000458 78460000 78640000 00000116 0000000D 00000002
    Addr: 7865F95C 78465290 00000458 00000E1E 0000001D 784653CC 00000000 78215C18
    Stck: 7861F91A 00000033 786477E9 00000021 00000033 00000000 7865C1D8 00000033
    Stck: 00000139 0000001D 784653CC 78000B4C 00000139 00000000 7865F95C 7865C2F4
    Stck: 00000000 7865C2F4 00000000 00000000 00000000 00000000 FF0300FF 00000F00
    Stck: 0001FFFF 01150009 EAEA2A2A 2A2A2A2A 00000000 7829721A 0100000B 00060008
    Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    Stck: 00000000 0114000B 0000FFF8 01130002 00000000 78620594 7865C1D8 786477E9
    Stck: 00000033 00000000 80000000 00000001 0000011D 00000017 00000001 00000000
    Stck: 00000000 0000001D 7864779C 00000008 786236DC 00000000 00217864 77E90000
    Stck: 000B0000 00010001 78643788 00000000 00000000 00000000 0000015A 00000000
    Stck: 78647876 7864783A 00000021 00000000 00000000 00000034 00000034 786477CC
    Stck: 0001B47E 00000000 01140000 000B0000 00210000 00000000 01350000 000B0000
    Stck: 00020000 00000001 0000E3E6 7864756C 00000001 0000011D 786455C0 78465428
    Stck: 7861DC4A 786455C0 0000001D 7864779C 00000008 00000001 000001EE 0000011D
    Stck: 00000130 00000000 00000000 00000000 786455C0 785E8BE8 78645538 78000B4C
    Stck: 785E8BE8 7864756C 00000001 00000000 784654F8 78625E2C 786455C0 78612D52
    Stck: 786455C0 00000001 00000000 00000016 00000000 000001EE 0000011D 786455C0
    Name: "MUI"  

    Exception !!   00000002     TCB: 78460AE8     CTX: 78104FC0     SSP: 78215C18
    USP : 78465250 SR: 0000  (U0)(-)(-)  TCB: 78460AE8
    Data: 78650000 00000000 00000458 78460000 78640000 00000116 0000000D 00000002
    Addr: 7865F95C 78465290 00000458 00000E1E 0000001D 784653CC 00000000 78215C18
    Stck: 7861F91A 00000033 786477E9 00000021 00000033 00000000 7865C1D8 00000033
    Stck: 00000139 0000001D 784653CC 78000B4C 00000139 00000000 7865F95C 7865C2F4
    Stck: 00000000 7865C2F4 00000000 00000000 00000000 00000000 FF0300FF 00000F00
    Stck: 0001FFFF 01150009 EAEA2A2A 2A2A2A2A 00000000 7829721A 0100000B 00060008
    Stck: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    Stck: 00000000 0114000B 0000FFF8 01130002 00000000 78620594 7865C1D8 786477E9
    Stck: 00000033 00000000 80000000 00000001 0000011D 00000017 00000001 00000000
    Stck: 00000000 0000001D 7864779C 00000008 786236DC 00000000 00217864 77E90000
    Stck: 000B0000 00010001 78643788 00000000 00000000 00000000 0000015A 00000000
    Stck: 78647876 7864783A 00000021 00000000 00000000 00000034 00000034 786477CC
    Stck: 0001B47E 00000000 01140000 000B0000 00210000 00000000 01350000 000B0000
    Stck: 00020000 00000001 0000E3E6 7864756C 00000001 0000011D 786455C0 78465428
    Stck: 7861DC4A 786455C0 0000001D 7864779C 00000008 00000001 000001EE 0000011D
    Stck: 00000130 00000000 00000000 00000000 786455C0 785E8BE8 78645538 78000B4C
    Stck: 785E8BE8 7864756C 00000001 00000000 784654F8 78625E2C 786455C0 78612D52
    Stck: 786455C0 00000001 00000000 00000016 00000000 000001EE 0000011D 786455C0
    Name: "MUI"

**Comment by tboeckel** [comment]
I am still not able to reproduce this issue.

Here is a debug build of TE.mcc 15.51. Just unpack the archive and copy "TextEditor.mcc.debug" to your MUI classes directory as "TextEditor.mcc". Then try to reproduce the crash. The resulting crashlog will then point to locations in the code which I can translate into files/line numbers.

[TE.mcc_debug_15.51.zip](https://github.com/amiga-mui/texteditor/files/2956513/TE.mcc_debug_15.51.zip)

**Comment by Gerbinist** [comment]
Thanks for looking into this Thore. Could you share some hints on how to actually obtain any debug logs? As per [this site](https://muidev.de/wiki/FAQ/Debugging) I did the following "just to be sure":

    setenv muidebug all

I then started Sashimi, MUI Prefs and selected TextEditor, but the output is precisely 0...

**Comment by tboeckel** [comment]
ENV:muidebug controls the debugging facilities of MUI5 and is absolutely not related to TE.mcc. Furthermore you are still using MUI3. Hence setting this variable is even more useless.

The provided debug build does not produce any special output. It just contains debug symbols and further information to assist finding the location of a crash. I don't expect you to capture any debug messages, but just to reproduce the crash with that debug build. The resulting crash log will then contain the necessary information to derive file and line number of the crash.

**Comment by Gerbinist** [comment]
Ah, got you.

- ----> 78622C6C - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 000110C4

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 000110C4
PrintLineWithStyles.c: line 559, offset 0x110b2


- ----> 78625DB4 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001420C

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 0001420C
extrasrc/GetSucc.c: line 33, offset 0x1420c


- ----> 78620322 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0000E77A

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 0000E77A
MixedFunctions.c: line 681, offset 0xe764


- ----> 78628504 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001695C

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 0001695C
11.Ram Disk:>


- ----> 7861542A - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003882

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 00003882
Dispatcher.c: line 644, offset 0x3882


- ----> 78615B42 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003F9A

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 00003F9A
Dispatcher.c: line 931, offset 0x3f8e


- ----> 78615736 - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 00003B8E

  - 11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 00003B8E
Dispatcher.c: line 846, offset 0x3b8e

*EDIT: not entirely sure if these offsets can be trusted... the offsets that MuForce displays are the same for the debug and the non-debug version...
I verified multiple times that the debug version is actually in use (even booted from cold just to be 100% sure).

**Comment by Gerbinist** [comment]
The above examples were obtained by using:

    Run >NIL: <NIL: Utilities:System/MuTools/MuForce STACKLINES 32 STACKCHECK AREGCHECK FILE KCON:0/14/640/100/HIT/AUTO/WAIT

When using the following commandline I get a different offset:

    Run >NIL: <NIL: Utilities:System/MuTools/MuForce SHOWPC DATESTAMP STACKCHECK STACKLINES=2 DISPC DISRANGE=16 FILE KCON:0/14/640/100/HIT/AUTO/WAIT

Result:

    12-Mar-19  23:04:20
    WORD READ from FFFFFF88 (INST)                 PC: FFFFFF88
    USP : 78467868 SR: 0000  (U0)(-)(-)  TCB: 78463100
    Data: 78650000 00000000 00000458 78460000 78640000 00000116 0000000D 00000002
    Addr: 7865FF6C 784678A8 00000458 00000E1E 0000001D 784679E4 00000000 7820F1E0
    Stck: 785C285A 00000033 78649E29 00000021 00000033 00000000 7865E7E0 00000033
    Stck: 00000139 0000001D 784679E4 78000B4C 00000139 00000000 7865FF6C 7865E8AC
    ----> 785C285A - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001044A
    PC Address invalid
    Name: "MUI"  


    12-Mar-19  23:04:20
    Exception !!   00000002     TCB: 78463100     CTX: 78104FC0     SSP: 7820F1E0
    USP : 78467868 SR: 0000  (U0)(-)(-)  TCB: 78463100
    Data: 78650000 00000000 00000458 78460000 78640000 00000116 0000000D 00000002
    Addr: 7865FF6C 784678A8 00000458 00000E1E 0000001D 784679E4 00000000 7820F1E0
    Stck: 785C285A 00000033 78649E29 00000021 00000033 00000000 7865E7E0 00000033
    Stck: 00000139 0000001D 784679E4 78000B4C 00000139 00000000 7865FF6C 7865E8AC
    ----> 785C285A - "LIBS:mui/TextEditor.mcc"  Hunk 0000 Offset 0001044A
    PC Address invalid
    Name: "MUI"

FindHit:

    11.Ram Disk:> GccFindHit LIBS:mui/TextEditor.mcc 0001044A
    PrintLineWithStyles.c: line 133, offset 0x1044a

**Comment by tboeckel** [comment]
Ok, I think I found the reason for the crash. I suppose your system/screen is not able handle alpha channel and transparency and has no 3rd pary graphics system like Picasso96 or CyberGraphics installed. There was a slightly wrong check whether text should be displayed with transparency which in turn caused functions of cybergraphics.library to be called, which of coure must crash when it is not available.
[TE.mcc_debug_15.52.zip](https://github.com/amiga-mui/texteditor/files/2960089/TE.mcc_debug_15.52.zip)


Please test this pre-build of TE.mcc 15.52. It should fix the crash.

**Comment by Gerbinist** [comment]
Confirmed, thanks.

**Comment by javierdlr** [comment]
BTW with TE_15.52debug version I can't use wheelmouse when pointer is over on text container, it works when over slider but not on the container where text exists, with 15.51 no problems scrolling the wheelmouse when pointer is over the text container.
AmigaOS4.1FE upd1 + betas.
MUI svn r6433

**Comment by tboeckel** [comment]
Am 03.04.19 um 13:31 schrieb javierdlr:
> BTW with TE_15.52debug version I can't use wheelmouse when pointer is over on text container, it 
> works when over slider but not on the container where text exists, with 15.51 no problems scrolling 
> the wheelmouse when pointer is over the text container.
> AmigaOS4.1FE upd1 + betas.
> MUI svn r6433

This is a different issue than the original crash. Please open a separate ticket for separate 
issues. Furthermore TE 15.52 has been officially released yesterday. So please check whether the 
issue exists with the release version as well.

-- 
Thore Böckelmann
Rehmerloh, Germany

**Comment by javierdlr** [comment]
Sorry, tested with 15.52 and wheelmouse works fine. I deleted the comment, but it was already posted/sent.
Sorry again.
