### ISSUE TITLE
MUIM_TextEditor_CursorXYToIndex should indicate success/failure

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#24]
So `MUIM_TextEditor_IndexToCursorXY` returns a `BOOL` indicating whether the operation succeeded or not. I'd like `MUIM_TextEditor_CursorXYToIndex` to do that as well because currently it always returns something, even if the specified cursor indices are well out of range...

**Comment by tboeckel** [comment]
That method cannot fail. It always returns a valid index within the text. However, for positions outside the actual text range it will always return an index pointing to the end of the text.

**Comment by afalkenhahn** [comment]
Yes, and that should be changed or is there another way to check if a cursor x,y is within valid bounds?

**Comment by tboeckel** [comment]
Done. Please check the attached interim version of TE.mcc 15.53.
[MCC_TextEditor-15.53.lha.zip](https://github.com/amiga-mui/texteditor/files/3364641/MCC_TextEditor-15.53.lha.zip)

**Comment by afalkenhahn** [comment]
Works great! Thanks a lot!
