### ISSUE TITLE
AROS i-386 version 15.51 & 15.52 Text is invisible

### ISSUE THREAD

**Issue by NathanH13** [amiga-mui/texteditor#26]
I'm using MUI Royale for Hollywood on AROS i-386 and the text is invisible in my project and in the Hollywood example TextEditor.hws.  I've set the color to black in code but that makes no difference.  Version 15.45 works just fine.  Hollywood author believes it is a bug in 15.51 and not in MUI Royale.  Thanks for looking into it.

NathanH
riversidepapa@zoho.com

**Comment by tboeckel** [comment]
All I can imagine is that this is caused by the implementation of the RGB mode in 15.46. It seems the RGB color specifications are not correctly set for AROS. All other systems definitely work as expected.
Maybe AROS need the RPTAG_PenMode in any case, just like MorphOS...

**Comment by tboeckel** [comment]
[MCC_TextEditor-15.53.zip](https://github.com/amiga-mui/texteditor/files/3549649/MCC_TextEditor-15.53.zip)
This version is setting RPTAG_PenMode for AROS in every situation as well. Please try it.

**Comment by NathanH13** [comment]
The new version 15.53 fixes this issue.  Thank you very much!

Nathan
