### ISSUE TITLE
Setting MUIA_Font doesn't work at all

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#29]
Passing `MUIA_Font` to TextEditor.mcc on object creation doesn't seem to work at all. The special values `MUIV_Font_Big`, and `MUIV_Font_Tiny` have no effect. Setting `MUIA_Font` to a `struct TextFont` directly doesn't do anything either.

**Comment by tboeckel** [comment]
TextEditor class has its own settings options for normal and fixed font and hence ignores MUIA_Font. This is a design decision that has been made ages ago by the original developer and which cannot be reverted. MUIA_Font is set internally depending on MUIA_TextEditor_FixedFont.

**Comment by afalkenhahn** [comment]
So there is no way to change the font of a TextEditor except making it fixed through MUIA_TextEditor_FixedFont?

**Comment by tboeckel** [comment]
Yes, exactly. I know, this is unfortunate from you POV, but it cannot be changed, at least not with an the small amount of work I am willing to spend on this project.

TextEditor.mcc is a par excellence example of how NOT to design a MUI custom class. There many, many more things in there, which are implemented in a either wrong or at least very ugly way. One of these extremely ugly ways is how OM_SET is handled, which you are currently experiences with double popup menu triggers. The handling of almost all methods is nested in a top level MUI_Redraw() call to comply with MUI's rule of doing rendering operations in MUIM_Draw only. This now effectively calls OM_SET twice and hence causes the double trigger. Now I must find a way to avoid these double triggers while keeping the rest alive as it was before :(

**Comment by afalkenhahn** [comment]
But I don't see why implementing support for other fonts should be such a huge endeavour? I mean, the code is already there since you can set a font in the TextEditor prefs. What keeps you from simply adding a new tag to override the prefs font with a different one? Sounds like a quick job to me.

**Comment by tboeckel** [comment]
[te_custom_font.zip](https://github.com/amiga-mui/texteditor/files/5073030/te_custom_font.zip)
Test binaries for AmigaOS3 and AmigaOS4

**Comment by afalkenhahn** [comment]
Thanks, works fine. Can you also provide non-debug builds please?

**Comment by tboeckel** [comment]
The binaries just contain debug symbols, but no debug code. They are not meant to be distributed in any way as they have non-bumped versions compared to the latest release.
