### ISSUE TITLE
Italicizing underlined text doesn't work

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#3]
Run the attached sample. Mark the word "Hello". Then click on the "Italic" button. The text will now vanish completely (see screenshot). 
![shot](https://cloud.githubusercontent.com/assets/6772528/14936961/b0c73bfc-0ef9-11e6-88d9-296675112df3.png)
[TextEditor-Demo.txt](https://github.com/amiga-mui/texteditor/files/243690/TextEditor-Demo.txt)

**Comment by tboeckel** [comment]
Unfortunately github again refuses to accept my attachments, even if the .zip archive is created on Linux instead of Windows :(
I will send the test binaries in private again.
