### ISSUE TITLE
Wrong mouse pointer when context menu is open

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#30]
When opening a context menu attached to a TextEditor gadget, the TextEditor gadget will still show its custom mouse pointer. This looks a little awkward. It should better show the system mouse pointer when opening a context menu because otherwise you have to select a context menu item using the custom TextEditor pointer which feels a little weird.

**Comment by tboeckel** [comment]
This is in fact an issue of MUI itself. The next nightly build of MUI5 will set a normal pointer before opening a popup menu.
