### ISSUE TITLE
Get cursor index from mouse position

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/texteditor#35]
Is it possible to get the cursor index at a specified mouse position? e.g. something similar to `MUIM_List_TestPos` , just for the text editor class. Could be useful for showing customized context menus on `MUIM_ContextMenuBuild`.

**Comment by tboeckel** [comment]
Here is a prerelease of TextEditor 15.56 including the updated headers and a tiny example code embedded into TextEditor-Demo.
[MCC_TextEditor-15.56.zip](https://github.com/amiga-mui/texteditor/files/6613563/MCC_TextEditor-15.56.zip)

**Comment by afalkenhahn** [comment]
Thanks, this seems to be working nicely. I have one more request, though: I think it would make more sense if -1 was returned when the mouse position is over an area that has no text. For example, take a look at this screenshot:

![Ohne Titel-2](https://user-images.githubusercontent.com/6772528/123510874-3cd8da00-d67e-11eb-8c15-7441be4a4668.png)

If I use `MUIM_TextEditor_TestPos` on the position of the mouse pointer (bottom right area of the gadget), it will still return index 5. I think it should return -1 instead because there is no text at this mouse position. An index should only be returned if the mouse is actually over text.
