### ISSUE TITLE
Using copy keysstroke (Amiga+C) to copy to clipboard some text crashes/GR

### ISSUE THREAD

**Issue by javierdlr** [amiga-mui/texteditor#4]
With TE.mcc V15.47 using copy keysstroke (Amiga+C) to copy to clipboard some text crashes/GR, tested with TextEditor.mcc 15.46 no problems using AMIGA+C keystroke to copy to clipboard text:

Crash log for task "TextEditor.mcc clipboard server"
Generated by GrimReaper 53.19
Crash occured in module TextEditor.mcc at address 0x7F8A69E8
Type of crash: DSI (Data Storage Interrupt) exception
Alert number: 0x80000003

Register dump:
GPR (General Purpose Registers):
   0: 7F8A4CD0 5E2AEEF0 00000000 FEFECAFE 5E2AEF1C 0002D030 0229AE0C 0229AE7C 
   8: 00000033 00000001 00000001 0218974C 48842428 00000000 5288DFA0 DEADF00D 
  16: FEFECAFE 434F4C53 53424152 43534554 00000000 00000013 5EA60000 5E548DB0 
  24: 464C4F57 5EA589C0 5E696D90 5EA5990C 00000013 0218974C 7FFFFFFF 5EA59900 

FPR (Floating Point Registers, NaN = Not a Number):
   0:                0                0                0                0 
   4:                0                0                0                0 
   8:                0                0                0                0 
  12:                0                0                0                0 
  16:                0                0                0                0 
  20:                0                0                0                0 
  24:                0                0                0                0 
  28:                0                0                0                0 

FPSCR (Floating Point Status and Control Register): 0x00000000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002D030
                Condition (cr) : 0x00000000
      Instruction Pointer (ip) : 0x7F8A69E8
       Xtended Exception (xer) : 0x50E10490
                   Count (ctr) : 0x00000000
                     Link (lr) : 0x509F1E80
            DSI Status (dsisr) : 0x57616974
            Data Address (dar) : 0x509F1DA8

680x0 emulated registers:
DATA: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x7F8A69E8 belongs to module "TextEditor.mcc" (PowerPC) 
Symbol: SetDefaultColor + 0x8 in section 1 offset 0x000049E4

Stack trace:
    LIBS:mui/TextEditor.mcc:SetDefaultColor()+0x8 (section 1 @ 0x49E4)
    LIBS:mui/TextEditor.mcc:ClipboardServer()+0x248 (section 1 @ 0x2D40)
    native kernel module kernel.debug+0x00067e40
    native kernel module kernel.debug+0x00067e88

PPC disassembly:
 7f8a69e0: 2c030000   cmpwi             r3,0
 7f8a69e4: 41820010   beq-              0x7F8A69F4
*7f8a69e8: a923043c   lha               r9,1084(r3)
 7f8a69ec: 2f890001   cmpwi             cr7,r9,1
 7f8a69f0: 419e0018   beq-              cr7,0x7F8A6A08

System information:

CPU 
 Model: AMCC PPC460EX V1.2 
 CPU speed: 1155 MHz 
 FSB speed: 231 MHz 
 Extensions:  

Machine 
 Machine name: Sam460ex 
 Memory: 2097152 KB 
 Extensions: bus.pci bus.pcie 
[crashlog_TE.mcc-clipboard server.txt](https://github.com/amiga-mui/texteditor/files/411442/crashlog_TE.mcc-clipboard.server.txt)

**Comment by tboeckel** [comment]
Here are some fixed binaries for AmigaOS3 and AmigaOS4 for testing.

[te_os3.zip](https://github.com/amiga-mui/texteditor/files/412831/te_os3.zip)
[te_os4.zip](https://github.com/amiga-mui/texteditor/files/412832/te_os4.zip)

I really HATE github's attachment facilities. With Firefox the files are rejected on both Linux and Windows, but with Chrome everything works, at least on Linux. Can someone please tell me what exactly the difference is?

**Comment by javierdlr** [comment]
tested os4 fixed binaty and no problems using AMIGA+C to copy text.

About the attachment files: even if you click on 'SELECTING THEM'? I did it that way under AOS4 Odyssey

THX

**Comment by tboeckel** [comment]
It doesn't matter whether I use Drag&Drop or a file requester. It is definitely a matter of the used browser and possibly of the used operating system. And what is most frustrating that no Amiga browser is involved here, but 100% up-to-date browsers on mainstream systems.
