### ISSUE TITLE
Crash when copying in YAM

### ISSUE THREAD

**Issue by pferrucci** [amiga-mui/texteditor#5]
Since the last update a few days ago, I have a crash when I select some text and type Amiga-C to copy it in the clipboard.
It is 100% reproducible.

Registers pointing to code:
r0 : LIBS:mui/TextEditor.mcc:ClipboardServer()+0x1d4 (section 1 @ 0x2CCC)
r6 : native kernel module Kickstart/kernel+0x00a8ade8
r10: module LIBS:mui/Frimagedisplay.mui at 0x00000001 (section 0 @ 0xFFFFFFDC)
r11: native kernel module Kickstart/kernel+0x0097972c
r27: LIBS:mui/TextEditor.mcc:msg()+0x0 (section 11 @ 0xC)
r29: native kernel module Kickstart/kernel+0x0097972c
r31: LIBS:mui/TextEditor.mcc:IIFFParse()+0x0 (section 11 @ 0x0)
ip : LIBS:mui/TextEditor.mcc:SetDefaultColor()+0x8 (section 1 @ 0x49E4)
lr : LIBS:mui/TextEditor.mcc:ClipboardServer()+0x248 (section 1 @ 0x2D40)
ctr: native kernel module Kickstart/kernel+0x00010498

Stack trace:
(0x60C50EF0) LIBS:mui/TextEditor.mcc:SetDefaultColor()+0x8 (section 1 @ 0x49E4)
(0x60C50F90) LIBS:mui/TextEditor.mcc:ClipboardServer()+0x248 (section 1 @ 0x2D40)
(0x60C50FC0) native kernel module Kickstart/kernel+0x0003b9dc
(0x60C50FD0) native kernel module Kickstart/kernel+0x0003ba24

Disassembly of crash site:
 7F6FA9D8: 409EFF30   bne+              cr7,0x7F6FA908
 7F6FA9DC: 4BFFFEA8   b                 0x7F6FA884
 7F6FA9E0: 2C030000   cmpwi             r3,0
 7F6FA9E4: 41820010   beq-              0x7F6FA9F4

> 7F6FA9E8: A923043C   lha               r9,1084(r3)
>  7F6FA9EC: 2F890001   cmpwi             cr7,r9,1
>  7F6FA9F0: 419E0018   beq-              cr7,0x7F6FAA08
>  7F6FA9F4: 39200000   li                r9,0
>  7F6FA9F8: 39400000   li                r10,0
>  7F6FA9FC: B1240004   sth               r9,4(r4)
> Stack pointer (0x60C50EF0) is inside bounds
> Redzone is OK (4)

Tell me if you need more.

**Comment by tboeckel** [comment]
This has been been reported as #4 and has been fixed already, too. Fixed binaries for AmigaOS4 and AmigaOS3 can be found at issue #4.

**Comment by pferrucci** [comment]
Doh, I completely forgot about it and I didn't even installed the fixed binary. Now I did. It works. Thanks.
