### ISSUE TITLE
crash/GR when usnig AMIGA+C (copy to clipboard)

### ISSUE THREAD

**Issue by javierdlr** [amiga-mui/texteditor#6]
Ig et a crash/GR when trying to copy text to clipboard (Amiga+C). Using MUI5 nightly build. and TextEditor.mcc from MUI5_contrib archive.
# version TextEditor.mcc full file

TextEditor.mcc 15.47 [OS4/PPC](6-08-2016)
Copyright (C) 2005-2015 TextEditor.mcc Open Source Team
# list TextEditor.mcc

TextEditor.mcc               171068 ----rwed Martes    23:34:09
1 fichero - 167K bytes - 336 bloques usados
# md5sum TextEditor.mcc

909767f6b7d4bb4bcac50f24a291aaa5  TextEditor.mcc

Crash log for task "TextEditor.mcc clipboard server"
Generated by GrimReaper 53.19
Crash occured in module TextEditor.mcc at address 0x7F8A69E8
Type of crash: DSI (Data Storage Interrupt) exception
Alert number: 0x80000003

Register dump:
GPR (General Purpose Registers):
   0: 7F8A4CD0 5D6B5EF0 00000000 FEFECAFE 5D6B5F1C 0002D030 0229AE0C 0229AE7C 
   8: 00000021 00000001 00000001 0218974C 48842428 00000000 5D36A450 DEADF00D 
  16: FEFECAFE 434F4C53 53424152 43534554 00000000 00000032 5DE90000 5B87F1A0 
  24: 464C4F57 5D6D85C0 5D1E1630 5DE9290C 00000001 0218974C 7FFFFFFF 5DE92900 

FPR (Floating Point Registers, NaN = Not a Number):
   0:                0                0                0                0 
   4:                0                0                0                0 
   8:                0                0                0                0 
  12:                0                0                0                0 
  16:                0                0                0                0 
  20:                0                0                0                0 
  24:                0                0                0                0 
  28:                0                0                0                0 

FPSCR (Floating Point Status and Control Register): 0x00000000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002D030
                Condition (cr) : 0x5F302F2C
      Instruction Pointer (ip) : 0x7F8A69E8
       Xtended Exception (xer) : 0x5AAA7018
                   Count (ctr) : 0x6FF5E4D0
                     Link (lr) : 0x7FC4F5E0
            DSI Status (dsisr) : 0x5AAA6DD0
            Data Address (dar) : 0x01ACEC88

680x0 emulated registers:
DATA: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x7F8A69E8 belongs to module "TextEditor.mcc" (PowerPC) 
Symbol: SetDefaultColor + 0x8 in section 1 offset 0x000049E4

Stack trace:
    LIBS:mui/TextEditor.mcc:SetDefaultColor()+0x8 (section 1 @ 0x49E4)
    LIBS:mui/TextEditor.mcc:ClipboardServer()+0x248 (section 1 @ 0x2D40)
    native kernel module kernel.debug+0x00067e40
    native kernel module kernel.debug+0x00067e88

PPC disassembly:
 7f8a69e0: 2c030000   cmpwi             r3,0
 7f8a69e4: 41820010   beq-              0x7F8A69F4
*7f8a69e8: a923043c   lha               r9,1084(r3)
 7f8a69ec: 2f890001   cmpwi             cr7,r9,1
 7f8a69f0: 419e0018   beq-              cr7,0x7F8A6A08

System information:

CPU 
 Model: AMCC PPC460EX V1.2 

[Crashlog.txt](https://github.com/amiga-mui/texteditor/files/449669/Crashlog.txt)

**Comment by javierdlr** [comment]
Oops, sorry forget to tri
[Crashlog.txt](https://github.com/amiga-mui/texteditor/files/449666/Crashlog.txt)
m filename

**Comment by tboeckel** [comment]
This is no surprise, because the version in MUI's contributions archive is exactly the one contained in the last TextEditor release archive. You have been reporting this bug yourself already as #4 and you know where to find the fixed, but yet officially unreleased binaries.

**Comment by javierdlr** [comment]
Ok. I thought as it was MUI5 it had the fixed TE.mcc
Sorry and THX.
